version: "3.7"

networks:
  ml_network:
    driver: bridge

volumes:
  local_postgres_data:
    name: "local_postgres_data"
  local_postgres_data_backups: 
    name: "local_postgres_data_backups"

services:
  backend:
    container_name: backend
    image: backend
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - backend/env/production/postgres
      - backend/env/production/app
    ports:
      - 5000:5000
    command: /app/start
    networks:
      - ml_network
    depends_on: 
      - db

  db:
    image: postgres
    container_name: db
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file: 
      - backend/env/production/postgres
    networks: 
      - ml_network

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      - backend
      - db
    networks:
      - ml_network