version: "3.7"

services: 
    notebook: &notebook
        container_name: notebook
        image: notebook_ml:1.0
        build: .
        env_file:
            - .env
        volumes:
            - .:/app
        ports: 
            - 8888:8888
        command: jupyter notebook --allow-root --port=8888 --no-browser --ip=0.0.0.0
    
    mlflow:
        <<: *notebook
        image: mlflow_ml:1.0
        container_name: mlflow
        ports:
            - 5000:5000
        command: mlflow ui -p 5000 -h 0.0.0.0